#!/bin/sh

# Find out the user who calls the script no matter if called as sudo or not.

set -e

USER_NAME="$SUDO_USER"

if [ -n "$SUDO_USER" ]
then
	echo "$USER_NAME"
else
	USER_NAME=$(whoami)
	if [ "$USER_NAME" = "root" ]
	then
		USER_NAME=$(logname)
	fi
	echo $USER_NAME
fi
