#!/bin/sh

# Aus $irgendwelchen Gründen hängt sich der Dovecot manchmal weg und vergisst sein Zertifikat
# -> Neustart hilft

TS=$(date +%Y-%m-%dT%T.%6N%:z)
DATE=$(date +%FT%T)
HOST=$(hostname)

FAIL=$(grep -i "sslv3 alert certificate unknown" /var/log/mail.log | grep "$DATE")

if [ -n "$FAIL" ]
then
	echo "$TS $HOST dovecot: Restarting dovecot because of certificate error" >> /var/log/mail.log
	service dovecot restart >/dev/null
fi
